<?php

use Illuminate\Database\Seeder;

class AttachmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attachments')->delete();
        
        \DB::table('attachments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'filename' => 'ID1.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/205/ID1.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '159.4 KB',
                'attachable_id' => 205,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-11-01 16:35:46',
                'updated_at' => '2015-11-01 16:35:46',
            ),
            1 => 
            array (
                'id' => 2,
                'filename' => 'ID2.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/205/ID2.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '163.4 KB',
                'attachable_id' => 205,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-11-01 16:35:46',
                'updated_at' => '2015-11-01 16:35:46',
            ),
            2 => 
            array (
                'id' => 3,
                'filename' => 'ID1.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/206/ID1.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '150.1 KB',
                'attachable_id' => 206,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-11-01 16:57:40',
                'updated_at' => '2015-11-01 16:57:40',
            ),
            3 => 
            array (
                'id' => 4,
                'filename' => 'ID2.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/206/ID2.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '154 KB',
                'attachable_id' => 206,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-11-01 16:57:40',
                'updated_at' => '2015-11-01 16:57:40',
            ),
            4 => 
            array (
                'id' => 5,
                'filename' => 'ID1.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/149/ID1.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '445.9 KB',
                'attachable_id' => 149,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-11-20 14:43:55',
                'updated_at' => '2015-11-20 14:43:55',
            ),
            5 => 
            array (
                'id' => 6,
                'filename' => 'ID2.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/149/ID2.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '512.3 KB',
                'attachable_id' => 149,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-11-20 14:43:55',
                'updated_at' => '2015-11-20 14:43:55',
            ),
            6 => 
            array (
                'id' => 7,
                'filename' => 'IMG-20151130-WA0007.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/299/IMG-20151130-WA0007.jpg',
                'attached_by' => 17,
                'attachment_owner' => 17,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '381.9 KB',
                'attachable_id' => 299,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2015-12-20 13:49:04',
                'updated_at' => '2015-12-20 13:49:04',
            ),
            7 => 
            array (
                'id' => 8,
                'filename' => 'IMG-20160105-WA0009.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/392/IMG-20160105-WA0009.jpg',
                'attached_by' => 17,
                'attachment_owner' => 17,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '403.7 KB',
                'attachable_id' => 392,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-01-05 23:32:32',
                'updated_at' => '2016-01-05 23:32:32',
            ),
            8 => 
            array (
                'id' => 9,
                'filename' => '1.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2402/1.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '2.3 MB',
                'attachable_id' => 2402,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-03-16 14:56:54',
                'updated_at' => '2016-03-16 14:56:54',
            ),
            9 => 
            array (
                'id' => 10,
                'filename' => '2.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2402/2.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '2.3 MB',
                'attachable_id' => 2402,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-03-16 14:58:54',
                'updated_at' => '2016-03-16 14:58:54',
            ),
            10 => 
            array (
                'id' => 11,
                'filename' => '0975ea873344579f48c81c08b6268565.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2426/0975ea873344579f48c81c08b6268565.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '120.9 KB',
                'attachable_id' => 2426,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-03-23 15:24:37',
                'updated_at' => '2016-03-23 15:24:37',
            ),
            11 => 
            array (
                'id' => 12,
                'filename' => 'Untitled.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2868/Untitled.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '271.2 KB',
                'attachable_id' => 2868,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-10 14:52:22',
                'updated_at' => '2016-06-10 14:52:22',
            ),
            12 => 
            array (
                'id' => 13,
                'filename' => '1.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2878/1.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '139.9 KB',
                'attachable_id' => 2878,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-10 15:10:48',
                'updated_at' => '2016-06-10 15:10:48',
            ),
            13 => 
            array (
                'id' => 14,
                'filename' => '2.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2878/2.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '173.4 KB',
                'attachable_id' => 2878,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-10 15:11:05',
                'updated_at' => '2016-06-10 15:11:05',
            ),
            14 => 
            array (
                'id' => 15,
                'filename' => '1.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/1.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '88.4000000000000',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:20:13',
                'updated_at' => '2016-06-13 19:20:13',
            ),
            15 => 
            array (
                'id' => 16,
                'filename' => '2.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/2.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '110.5 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:20:23',
                'updated_at' => '2016-06-13 19:20:23',
            ),
            16 => 
            array (
                'id' => 17,
                'filename' => '3.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/3.jpg',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '17.8 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:20:32',
                'updated_at' => '2016-06-13 19:20:32',
            ),
            17 => 
            array (
                'id' => 18,
                'filename' => '4.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/4.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '28 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:20:40',
                'updated_at' => '2016-06-13 19:20:40',
            ),
            18 => 
            array (
                'id' => 19,
                'filename' => '5.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/5.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '27.4 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:20:52',
                'updated_at' => '2016-06-13 19:20:52',
            ),
            19 => 
            array (
                'id' => 20,
                'filename' => '6.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/6.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '26.7 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:21:01',
                'updated_at' => '2016-06-13 19:21:01',
            ),
            20 => 
            array (
                'id' => 21,
                'filename' => '7.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/7.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '117.9 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:21:12',
                'updated_at' => '2016-06-13 19:21:12',
            ),
            21 => 
            array (
                'id' => 22,
                'filename' => '8.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/8.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '462.7 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:21:32',
                'updated_at' => '2016-06-13 19:21:32',
            ),
            22 => 
            array (
                'id' => 23,
                'filename' => '9.JPG',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/2715/9.JPG',
                'attached_by' => 7,
                'attachment_owner' => 7,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '482 KB',
                'attachable_id' => 2715,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2016-06-13 19:21:52',
                'updated_at' => '2016-06-13 19:21:52',
            ),
            23 => 
            array (
                'id' => 24,
                'filename' => '15871340_1197681233602593_406805299_n.png',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/4806/15871340_1197681233602593_406805299_n.png',
                'attached_by' => 20,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '346.7 KB',
                'attachable_id' => 4806,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-01-04 15:52:25',
                'updated_at' => '2017-03-05 14:11:43',
            ),
            24 => 
            array (
                'id' => 25,
                'filename' => '15871340_1197681233602593_406805299_n.png',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/4806/15871340_1197681233602593_406805299_n.png',
                'attached_by' => 20,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '346.7 KB',
                'attachable_id' => 4806,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-01-04 15:52:49',
                'updated_at' => '2017-03-05 14:11:43',
            ),
            25 => 
            array (
                'id' => 26,
                'filename' => '15871340_1197681233602593_406805299_n.png',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/4806/15871340_1197681233602593_406805299_n.png',
                'attached_by' => 20,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '346.7 KB',
                'attachable_id' => 4806,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-01-04 15:53:53',
                'updated_at' => '2017-03-05 14:11:43',
            ),
            26 => 
            array (
                'id' => 27,
                'filename' => 'ID. Hagar Mohamed.pdf',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/5312/ID. Hagar Mohamed.pdf',
                'attached_by' => 28,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '426.8 KB',
                'attachable_id' => 5312,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-02-15 13:24:51',
                'updated_at' => '2017-02-15 13:24:51',
            ),
            27 => 
            array (
                'id' => 28,
                'filename' => 'ID. Mohamed Hussein.pdf',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/5312/ID. Mohamed Hussein.pdf',
                'attached_by' => 28,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '219.4 KB',
                'attachable_id' => 5312,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-02-15 13:24:51',
                'updated_at' => '2017-02-15 13:24:51',
            ),
            28 => 
            array (
                'id' => 29,
                'filename' => 'Eng. Ahmed El Deghedy.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/5432/Eng. Ahmed El Deghedy.jpg',
                'attached_by' => 28,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '137.5 KB',
                'attachable_id' => 5432,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-02-19 14:00:08',
                'updated_at' => '2017-02-19 14:00:08',
            ),
            29 => 
            array (
                'id' => 30,
                'filename' => 'Mrs.Reda Mahmoud Kamel.jpg',
                'filepath' => '/home/nexthomeegy/public_html/_vertex/public/uploads/Client/5439/Mrs.Reda Mahmoud Kamel.jpg',
                'attached_by' => 28,
                'attachment_owner' => 28,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '113 KB',
                'attachable_id' => 5439,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-02-19 14:02:58',
                'updated_at' => '2017-02-19 14:02:58',
            ),
            30 => 
            array (
                'id' => 31,
                'filename' => 'DSC_0817.jpg',
                'filepath' => '/home/vertexa/public_html/nexthome/public/uploads/Client/7030/DSC_0817.jpg',
                'attached_by' => 29,
                'attachment_owner' => 29,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '1.7 MB',
                'attachable_id' => 7030,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-07-09 16:40:41',
                'updated_at' => '2017-07-09 16:40:41',
            ),
            31 => 
            array (
                'id' => 32,
                'filename' => 'WhatsApp Image 2017-08-05 at 11.44.33 AM.jpeg',
                'filepath' => '/home/vertexa/public_html/nexthome/public/uploads/Client/7195/WhatsApp Image 2017-08-05 at 11.44.33 AM.jpeg',
                'attached_by' => 29,
                'attachment_owner' => 29,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '132.3 KB',
                'attachable_id' => 7195,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-08-05 11:46:21',
                'updated_at' => '2017-08-05 11:46:21',
            ),
            32 => 
            array (
                'id' => 33,
                'filename' => 'WhatsApp Image 2017-08-05 at 11.44.34 AM.jpeg',
                'filepath' => '/home/vertexa/public_html/nexthome/public/uploads/Client/7195/WhatsApp Image 2017-08-05 at 11.44.34 AM.jpeg',
                'attached_by' => 29,
                'attachment_owner' => 29,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '161 KB',
                'attachable_id' => 7195,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-08-05 11:46:21',
                'updated_at' => '2017-08-05 11:46:21',
            ),
            33 => 
            array (
                'id' => 34,
                'filename' => 'WhatsApp Image 2017-09-28 at 3.07.16 PM.jpeg',
                'filepath' => '/home/vertexa/public_html/nexthome/public/uploads/Client/7668/WhatsApp Image 2017-09-28 at 3.07.16 PM.jpeg',
                'attached_by' => 29,
                'attachment_owner' => 31,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'marked_deleted' => 0,
                'size' => '148.7 KB',
                'attachable_id' => 7668,
                'attachable_type' => '\\App\\Models\\Client',
                'created_at' => '2017-09-28 15:11:45',
                'updated_at' => '2017-10-11 15:14:19',
            ),
        ));
        
        
    }
}