<?php

use Illuminate\Database\Seeder;

class ClientPropertiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('client_properties')->delete();
        
        \DB::table('client_properties')->insert(array (
            0 => 
            array (
                'id' => 5,
                'project_id' => 8,
                'unit_id' => NULL,
                'price' => 1360000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 10,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2015-10-19 19:57:59',
                'month' => 10,
                'year' => 2015,
                'comment' => NULL,
                'created_at' => '2015-10-19 19:54:39',
                'updated_at' => '2015-10-19 19:57:59',
            ),
            1 => 
            array (
                'id' => 6,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 576000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 205,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2015-11-01 16:30:37',
                'month' => 11,
                'year' => 2015,
                'comment' => NULL,
                'created_at' => '2015-11-01 16:30:10',
                'updated_at' => '2015-11-01 16:30:37',
            ),
            2 => 
            array (
                'id' => 7,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 576000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 206,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2015-11-01 16:44:36',
                'month' => 11,
                'year' => 2015,
                'comment' => NULL,
                'created_at' => '2015-11-01 16:41:24',
                'updated_at' => '2015-11-01 16:44:36',
            ),
            3 => 
            array (
                'id' => 8,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 2791000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 149,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2015-11-20 14:40:44',
                'month' => 11,
                'year' => 2015,
                'comment' => NULL,
                'created_at' => '2015-11-20 14:40:01',
                'updated_at' => '2015-11-20 14:40:44',
            ),
            4 => 
            array (
                'id' => 9,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 2032000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 294,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2015-11-25 18:57:11',
                'month' => 11,
                'year' => 2015,
                'comment' => NULL,
                'created_at' => '2015-11-25 18:56:51',
                'updated_at' => '2015-11-25 18:57:11',
            ),
            5 => 
            array (
                'id' => 10,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 600000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 299,
                'created_by' => 17,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2015-12-20 13:50:25',
                'month' => 12,
                'year' => 2015,
                'comment' => NULL,
                'created_at' => '2015-12-20 13:47:20',
                'updated_at' => '2015-12-20 13:50:25',
            ),
            6 => 
            array (
                'id' => 11,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 956400.0,
                'propertable_type' => 'Project',
                'propertable_id' => 392,
                'created_by' => 17,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-01-06 00:00:16',
                'month' => 1,
                'year' => 2016,
                'comment' => 'Wrong Data',
                'created_at' => '2016-01-05 23:29:56',
                'updated_at' => '2016-01-06 00:00:16',
            ),
            7 => 
            array (
                'id' => 12,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 517200.0,
                'propertable_type' => 'Project',
                'propertable_id' => 392,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-01-06 00:08:15',
                'month' => 1,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-01-06 00:07:27',
                'updated_at' => '2016-01-06 00:08:15',
            ),
            8 => 
            array (
                'id' => 13,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 439200.0,
                'propertable_type' => 'Project',
                'propertable_id' => 392,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-01-06 00:10:46',
                'month' => 1,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-01-06 00:09:14',
                'updated_at' => '2016-01-06 00:10:46',
            ),
            9 => 
            array (
                'id' => 14,
                'project_id' => 10,
                'unit_id' => NULL,
                'price' => 463600.0,
                'propertable_type' => 'Project',
                'propertable_id' => 398,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-03-16 15:56:34',
                'month' => 3,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-03-16 12:14:44',
                'updated_at' => '2016-03-16 15:56:34',
            ),
            10 => 
            array (
                'id' => 15,
                'project_id' => 21,
                'unit_id' => NULL,
                'price' => 3596500.0,
                'propertable_type' => 'Project',
                'propertable_id' => 2402,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-03-18 22:11:13',
                'month' => 3,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-03-18 22:10:56',
                'updated_at' => '2016-03-18 22:11:13',
            ),
            11 => 
            array (
                'id' => 16,
                'project_id' => 11,
                'unit_id' => NULL,
                'price' => 2004000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 2426,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-03-23 15:35:01',
                'month' => 3,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-03-23 15:34:38',
                'updated_at' => '2016-03-23 15:35:01',
            ),
            12 => 
            array (
                'id' => 17,
                'project_id' => NULL,
                'unit_id' => 1,
                'price' => 20000.0,
                'propertable_type' => 'Unit',
                'propertable_id' => 2868,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-06-10 14:46:14',
                'month' => 6,
                'year' => 2016,
                'comment' => '',
                'created_at' => '2016-06-10 14:45:38',
                'updated_at' => '2016-06-10 14:46:14',
            ),
            13 => 
            array (
                'id' => 18,
                'project_id' => NULL,
                'unit_id' => 1,
                'price' => 18000.0,
                'propertable_type' => 'Unit',
                'propertable_id' => 2868,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-06-10 14:48:45',
                'month' => 6,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-06-10 14:48:19',
                'updated_at' => '2016-06-10 14:48:45',
            ),
            14 => 
            array (
                'id' => 19,
                'project_id' => 11,
                'unit_id' => NULL,
                'price' => 2149000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 2715,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-06-13 19:29:44',
                'month' => 6,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-06-13 19:25:43',
                'updated_at' => '2016-06-13 19:29:44',
            ),
            15 => 
            array (
                'id' => 20,
                'project_id' => 11,
                'unit_id' => NULL,
                'price' => 2149000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 2715,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-06-13 19:30:46',
                'month' => 6,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-06-13 19:30:34',
                'updated_at' => '2016-06-13 19:30:46',
            ),
            16 => 
            array (
                'id' => 21,
                'project_id' => NULL,
                'unit_id' => 2,
                'price' => 18000.0,
                'propertable_type' => 'Unit',
                'propertable_id' => 2878,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-06-16 15:29:47',
                'month' => 6,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-06-16 15:29:27',
                'updated_at' => '2016-06-16 15:29:47',
            ),
            17 => 
            array (
                'id' => 22,
                'project_id' => 22,
                'unit_id' => NULL,
                'price' => 2440000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 3093,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2016-10-17 18:52:12',
                'month' => 10,
                'year' => 2016,
                'comment' => NULL,
                'created_at' => '2016-10-06 14:22:38',
                'updated_at' => '2016-10-17 18:52:12',
            ),
            18 => 
            array (
                'id' => 23,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 2909000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 4806,
                'created_by' => 20,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-01-03 17:08:09',
                'month' => 1,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-01-03 17:06:03',
                'updated_at' => '2017-01-03 17:08:09',
            ),
            19 => 
            array (
                'id' => 24,
                'project_id' => 23,
                'unit_id' => NULL,
                'price' => 4048700.0,
                'propertable_type' => 'Project',
                'propertable_id' => 5312,
                'created_by' => 28,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-02-19 11:50:09',
                'month' => 2,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-02-19 11:49:02',
                'updated_at' => '2017-02-19 11:50:09',
            ),
            20 => 
            array (
                'id' => 25,
                'project_id' => 24,
                'unit_id' => NULL,
                'price' => 5000000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 5471,
                'created_by' => 25,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-03-05 17:37:12',
                'month' => 3,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-03-05 17:36:38',
                'updated_at' => '2017-03-05 17:37:12',
            ),
            21 => 
            array (
                'id' => 26,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 434098000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 5140,
                'created_by' => 28,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-03-26 14:18:12',
                'month' => 3,
                'year' => 2017,
                'comment' => 'Wrong Total Price ',
                'created_at' => '2017-03-26 14:14:40',
                'updated_at' => '2017-03-26 14:18:12',
            ),
            22 => 
            array (
                'id' => 27,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 4340980.0,
                'propertable_type' => 'Project',
                'propertable_id' => 5140,
                'created_by' => 28,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-03-26 14:20:42',
                'month' => 3,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-03-26 14:20:17',
                'updated_at' => '2017-03-26 14:20:42',
            ),
            23 => 
            array (
                'id' => 28,
                'project_id' => 25,
                'unit_id' => NULL,
                'price' => 956100.0,
                'propertable_type' => 'Project',
                'propertable_id' => 5479,
                'created_by' => 29,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-04-04 17:44:38',
                'month' => 4,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-04-04 17:37:54',
                'updated_at' => '2017-04-04 17:44:38',
            ),
            24 => 
            array (
                'id' => 29,
                'project_id' => 22,
                'unit_id' => NULL,
                'price' => 1500000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 4712,
                'created_by' => 21,
                'updated_by' => 21,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 21,
                'status_updated_at' => '2017-04-19 16:47:20',
                'month' => 4,
                'year' => 2017,
                'comment' => 'tst',
                'created_at' => '2017-04-19 16:45:39',
                'updated_at' => '2017-04-19 16:47:20',
            ),
            25 => 
            array (
                'id' => 30,
                'project_id' => 27,
                'unit_id' => NULL,
                'price' => 1096880.0,
                'propertable_type' => 'Project',
                'propertable_id' => 6630,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-05-17 19:08:47',
                'month' => 5,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-05-17 19:07:11',
                'updated_at' => '2017-05-17 19:08:47',
            ),
            26 => 
            array (
                'id' => 31,
                'project_id' => 27,
                'unit_id' => NULL,
                'price' => 646409.0,
                'propertable_type' => 'Project',
                'propertable_id' => 6412,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-05-23 17:07:17',
                'month' => 5,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-05-22 17:59:39',
                'updated_at' => '2017-05-23 17:07:17',
            ),
            27 => 
            array (
                'id' => 32,
                'project_id' => 26,
                'unit_id' => NULL,
                'price' => 2700000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 6882,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-05-31 15:23:45',
                'month' => 5,
                'year' => 2017,
                'comment' => 'The Total Price Is Wrong ',
                'created_at' => '2017-05-31 14:14:29',
                'updated_at' => '2017-05-31 16:21:28',
            ),
            28 => 
            array (
                'id' => 33,
                'project_id' => 26,
                'unit_id' => NULL,
                'price' => 2734100.0,
                'propertable_type' => 'Project',
                'propertable_id' => 6882,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-05-31 16:13:20',
                'month' => 5,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-05-31 16:10:39',
                'updated_at' => '2017-05-31 16:13:20',
            ),
            29 => 
            array (
                'id' => 34,
                'project_id' => 28,
                'unit_id' => NULL,
                'price' => 952232.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7030,
                'created_by' => 29,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-07-20 16:48:13',
                'month' => 7,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-07-20 16:47:22',
                'updated_at' => '2017-07-20 16:48:13',
            ),
            30 => 
            array (
                'id' => 35,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 3193860.0,
                'propertable_type' => 'Project',
                'propertable_id' => 2426,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-07-24 19:10:20',
                'month' => 7,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-07-24 19:10:07',
                'updated_at' => '2017-07-24 19:10:20',
            ),
            31 => 
            array (
                'id' => 36,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 3128670.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7195,
                'created_by' => 29,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-08-05 16:05:01',
                'month' => 8,
                'year' => 2017,
                'comment' => 'Total Price 3.128.686 EGP',
                'created_at' => '2017-08-05 11:45:57',
                'updated_at' => '2017-08-05 16:05:01',
            ),
            32 => 
            array (
                'id' => 37,
                'project_id' => 12,
                'unit_id' => NULL,
                'price' => 3128690.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7195,
                'created_by' => 29,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-08-05 16:13:03',
                'month' => 8,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-08-05 16:06:23',
                'updated_at' => '2017-08-05 16:13:03',
            ),
            33 => 
            array (
                'id' => 38,
                'project_id' => 30,
                'unit_id' => NULL,
                'price' => 1591000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7027,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-08-08 14:35:37',
                'month' => 8,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-08-08 13:41:25',
                'updated_at' => '2017-08-08 14:35:37',
            ),
            34 => 
            array (
                'id' => 39,
                'project_id' => 27,
                'unit_id' => NULL,
                'price' => 1403000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7290,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-08-29 16:21:40',
                'month' => 8,
                'year' => 2017,
                'comment' => 'Wrong Total Price ',
                'created_at' => '2017-08-29 16:18:29',
                'updated_at' => '2017-08-29 16:21:40',
            ),
            35 => 
            array (
                'id' => 40,
                'project_id' => 27,
                'unit_id' => NULL,
                'price' => 1403420.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7290,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-08-29 16:23:11',
                'month' => 8,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-08-29 16:22:35',
                'updated_at' => '2017-08-29 16:23:11',
            ),
            36 => 
            array (
                'id' => 41,
                'project_id' => 30,
                'unit_id' => NULL,
                'price' => 933000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7290,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-13 12:38:04',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-13 12:34:28',
                'updated_at' => '2017-09-13 12:38:04',
            ),
            37 => 
            array (
                'id' => 42,
                'project_id' => 24,
                'unit_id' => NULL,
                'price' => 2927380.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7639,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-19 13:55:05',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-19 13:54:21',
                'updated_at' => '2017-09-19 13:55:06',
            ),
            38 => 
            array (
                'id' => 43,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 3.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7331,
                'created_by' => 29,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-19 17:32:56',
                'month' => 9,
                'year' => 2017,
                'comment' => 'Total Price 3.094.025 EGP ',
                'created_at' => '2017-09-19 17:26:47',
                'updated_at' => '2017-09-19 17:32:56',
            ),
            39 => 
            array (
                'id' => 44,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 3094020.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7331,
                'created_by' => 29,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-19 17:35:57',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-19 17:34:39',
                'updated_at' => '2017-09-19 17:35:57',
            ),
            40 => 
            array (
                'id' => 45,
                'project_id' => 31,
                'unit_id' => NULL,
                'price' => 197000000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7592,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-25 18:03:39',
                'month' => 9,
                'year' => 2017,
                'comment' => 'Wrong Total Price ',
                'created_at' => '2017-09-25 17:45:26',
                'updated_at' => '2017-09-25 18:03:39',
            ),
            41 => 
            array (
                'id' => 46,
                'project_id' => 31,
                'unit_id' => NULL,
                'price' => 19700000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7592,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-25 18:07:56',
                'month' => 9,
                'year' => 2017,
                'comment' => 'Wrong Total Price ',
                'created_at' => '2017-09-25 18:06:18',
                'updated_at' => '2017-09-25 18:07:56',
            ),
            42 => 
            array (
                'id' => 47,
                'project_id' => 31,
                'unit_id' => NULL,
                'price' => 1970000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7592,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-25 18:10:30',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-25 18:09:27',
                'updated_at' => '2017-09-25 18:10:30',
            ),
            43 => 
            array (
                'id' => 48,
                'project_id' => 24,
                'unit_id' => NULL,
                'price' => 1860790.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7442,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-26 17:16:47',
                'month' => 9,
                'year' => 2017,
                'comment' => 'Wrong Area',
                'created_at' => '2017-09-26 14:11:59',
                'updated_at' => '2017-09-26 17:16:47',
            ),
            44 => 
            array (
                'id' => 49,
                'project_id' => 24,
                'unit_id' => NULL,
                'price' => 1860790.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7442,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-26 17:20:53',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-26 17:19:55',
                'updated_at' => '2017-09-26 17:20:53',
            ),
            45 => 
            array (
                'id' => 50,
                'project_id' => 13,
                'unit_id' => NULL,
                'price' => 7986610.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7603,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-28 14:51:13',
                'month' => 9,
                'year' => 2017,
                'comment' => 'Project Name " Sky Condos "',
                'created_at' => '2017-09-27 23:05:28',
                'updated_at' => '2017-09-28 14:51:13',
            ),
            46 => 
            array (
                'id' => 51,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 7986610.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7603,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-28 15:39:42',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-28 15:13:36',
                'updated_at' => '2017-09-28 15:39:42',
            ),
            47 => 
            array (
                'id' => 52,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 3724000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7742,
                'created_by' => 30,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-09-30 13:33:09',
                'month' => 9,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-09-30 13:32:03',
                'updated_at' => '2017-09-30 13:33:09',
            ),
            48 => 
            array (
                'id' => 53,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 5900000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7695,
                'created_by' => 30,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-10-05 15:08:53',
                'month' => 10,
                'year' => 2017,
                'comment' => 'Wrong Total Price',
                'created_at' => '2017-10-03 10:31:40',
                'updated_at' => '2017-10-05 15:08:53',
            ),
            49 => 
            array (
                'id' => 54,
                'project_id' => 32,
                'unit_id' => NULL,
                'price' => 1477430.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7710,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-10-05 15:09:13',
                'month' => 10,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-10-05 15:00:24',
                'updated_at' => '2017-10-05 15:09:13',
            ),
            50 => 
            array (
                'id' => 55,
                'project_id' => 32,
                'unit_id' => NULL,
                'price' => 6549240.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7639,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-10-05 15:10:14',
                'month' => 10,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-10-05 15:01:23',
                'updated_at' => '2017-10-05 15:10:14',
            ),
            51 => 
            array (
                'id' => 56,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 5.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7695,
                'created_by' => 30,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-10-05 15:23:55',
                'month' => 10,
                'year' => 2017,
                'comment' => '.',
                'created_at' => '2017-10-05 15:22:42',
                'updated_at' => '2017-10-05 15:23:55',
            ),
            52 => 
            array (
                'id' => 57,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 591365000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7695,
                'created_by' => 30,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-10-05 15:28:12',
                'month' => 10,
                'year' => 2017,
                'comment' => '.',
                'created_at' => '2017-10-05 15:26:48',
                'updated_at' => '2017-10-05 15:28:12',
            ),
            53 => 
            array (
                'id' => 58,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 5913650.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7695,
                'created_by' => 30,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-10-05 15:29:52',
                'month' => 10,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-10-05 15:29:15',
                'updated_at' => '2017-10-05 15:29:52',
            ),
            54 => 
            array (
                'id' => 59,
                'project_id' => 25,
                'unit_id' => NULL,
                'price' => 1592100.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7668,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-11-02 16:40:44',
                'month' => 10,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-10-11 15:19:37',
                'updated_at' => '2017-11-02 16:40:44',
            ),
            55 => 
            array (
                'id' => 60,
                'project_id' => 26,
                'unit_id' => NULL,
                'price' => 3247680.0,
                'propertable_type' => 'Project',
                'propertable_id' => 8194,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-11-02 16:41:50',
                'month' => 11,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-11-02 16:35:08',
                'updated_at' => '2017-11-02 16:41:50',
            ),
            56 => 
            array (
                'id' => 61,
                'project_id' => 33,
                'unit_id' => NULL,
                'price' => 1924500.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7545,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-11-02 17:00:35',
                'month' => 11,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-11-02 16:53:44',
                'updated_at' => '2017-11-02 17:00:35',
            ),
            57 => 
            array (
                'id' => 62,
                'project_id' => 22,
                'unit_id' => NULL,
                'price' => 2700000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7349,
                'created_by' => 31,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-11-02 17:22:16',
                'month' => 11,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-11-02 17:15:54',
                'updated_at' => '2017-11-02 17:22:16',
            ),
            58 => 
            array (
                'id' => 63,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 2990000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7714,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 0,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-11-05 17:05:40',
                'month' => 11,
                'year' => 2017,
                'comment' => 'Total Price ',
                'created_at' => '2017-11-05 17:03:24',
                'updated_at' => '2017-11-05 17:05:40',
            ),
            59 => 
            array (
                'id' => 64,
                'project_id' => 29,
                'unit_id' => NULL,
                'price' => 2999000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7714,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2017-11-05 17:21:57',
                'month' => 11,
                'year' => 2017,
                'comment' => NULL,
                'created_at' => '2017-11-05 17:15:35',
                'updated_at' => '2017-11-05 17:21:57',
            ),
            60 => 
            array (
                'id' => 65,
                'project_id' => 35,
                'unit_id' => NULL,
                'price' => 1796400.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7714,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2018-01-09 10:45:00',
                'month' => 1,
                'year' => 2018,
                'comment' => NULL,
                'created_at' => '2018-01-09 10:42:16',
                'updated_at' => '2018-01-09 10:45:00',
            ),
            61 => 
            array (
                'id' => 66,
                'project_id' => 35,
                'unit_id' => NULL,
                'price' => 10577000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 7714,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2018-01-17 12:57:24',
                'month' => 1,
                'year' => 2018,
                'comment' => NULL,
                'created_at' => '2018-01-13 13:38:33',
                'updated_at' => '2018-01-17 12:57:24',
            ),
            62 => 
            array (
                'id' => 67,
                'project_id' => 36,
                'unit_id' => NULL,
                'price' => 4784000.0,
                'propertable_type' => 'Project',
                'propertable_id' => 8777,
                'created_by' => 33,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'approved' => 1,
                'pending' => 0,
                'status_updated_by' => 7,
                'status_updated_at' => '2018-01-17 14:51:46',
                'month' => 1,
                'year' => 2018,
                'comment' => NULL,
                'created_at' => '2018-01-17 13:44:02',
                'updated_at' => '2018-01-17 14:51:46',
            ),
        ));
        
        
    }
}