<?php

use Illuminate\Database\Seeder;

class ForecastTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('forecast')->delete();
        
        \DB::table('forecast')->insert(array (
            0 => 
            array (
                'id' => 1,
                'month' => 1,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-01-14 11:44:01',
                'updated_at' => '2016-01-14 11:47:54',
            ),
            1 => 
            array (
                'id' => 2,
                'month' => 2,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 23:09:56',
                'updated_at' => '2016-04-19 23:09:56',
            ),
            2 => 
            array (
                'id' => 3,
                'month' => 3,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 23:10:14',
                'updated_at' => '2016-04-19 23:10:14',
            ),
            3 => 
            array (
                'id' => 4,
                'month' => 4,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-04-19 23:10:30',
                'updated_at' => '2016-04-20 17:46:05',
            ),
            4 => 
            array (
                'id' => 5,
                'month' => 5,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-05-04 17:54:21',
                'updated_at' => '2016-05-04 17:54:21',
            ),
            5 => 
            array (
                'id' => 6,
                'month' => 6,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-06-15 13:28:08',
                'updated_at' => '2016-06-15 13:33:51',
            ),
            6 => 
            array (
                'id' => 7,
                'month' => 7,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-12-18 11:17:34',
                'updated_at' => '2016-12-18 11:31:55',
            ),
            7 => 
            array (
                'id' => 8,
                'month' => 8,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-12-18 11:17:54',
                'updated_at' => '2016-12-18 11:17:54',
            ),
            8 => 
            array (
                'id' => 9,
                'month' => 9,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-12-18 11:18:06',
                'updated_at' => '2016-12-18 11:18:06',
            ),
            9 => 
            array (
                'id' => 10,
                'month' => 10,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-12-18 11:18:19',
                'updated_at' => '2016-12-18 11:18:19',
            ),
            10 => 
            array (
                'id' => 11,
                'month' => 11,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-12-18 11:18:30',
                'updated_at' => '2016-12-18 11:18:30',
            ),
            11 => 
            array (
                'id' => 12,
                'month' => 12,
                'year' => 2016,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2016-12-18 11:18:42',
                'updated_at' => '2016-12-18 11:35:00',
            ),
            12 => 
            array (
                'id' => 13,
                'month' => 1,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-01-01 10:18:59',
                'updated_at' => '2017-01-01 10:18:59',
            ),
            13 => 
            array (
                'id' => 14,
                'month' => 2,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-02-03 14:17:12',
                'updated_at' => '2017-02-03 14:19:15',
            ),
            14 => 
            array (
                'id' => 15,
                'month' => 3,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-03-07 11:41:59',
                'updated_at' => '2017-03-07 11:41:59',
            ),
            15 => 
            array (
                'id' => 19,
                'month' => 4,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-04-19 17:20:08',
                'updated_at' => '2017-04-19 17:20:08',
            ),
            16 => 
            array (
                'id' => 20,
                'month' => 5,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-05-09 17:13:59',
                'updated_at' => '2017-05-09 17:14:19',
            ),
            17 => 
            array (
                'id' => 21,
                'month' => 6,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-06-08 16:53:04',
                'updated_at' => '2017-06-08 16:53:04',
            ),
            18 => 
            array (
                'id' => 22,
                'month' => 7,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-07-11 14:16:00',
                'updated_at' => '2017-07-30 18:28:12',
            ),
            19 => 
            array (
                'id' => 23,
                'month' => 8,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-07-30 18:29:10',
                'updated_at' => '2017-07-30 18:29:10',
            ),
            20 => 
            array (
                'id' => 24,
                'month' => 9,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-09-06 17:50:23',
                'updated_at' => '2017-09-06 17:50:23',
            ),
            21 => 
            array (
                'id' => 25,
                'month' => 10,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-10-05 15:10:42',
                'updated_at' => '2017-10-05 15:10:42',
            ),
            22 => 
            array (
                'id' => 26,
                'month' => 11,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-11-02 16:51:14',
                'updated_at' => '2017-11-02 16:51:14',
            ),
            23 => 
            array (
                'id' => 27,
                'month' => 12,
                'year' => 2017,
                'amount' => 3000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2017-12-29 17:07:37',
                'updated_at' => '2017-12-29 17:07:37',
            ),
            24 => 
            array (
                'id' => 28,
                'month' => 1,
                'year' => 2018,
                'amount' => 5000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-01-09 10:44:20',
                'updated_at' => '2018-01-09 10:44:20',
            ),
            25 => 
            array (
                'id' => 29,
                'month' => 2,
                'year' => 2018,
                'amount' => 5000000.0,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-02-03 15:49:12',
                'updated_at' => '2018-02-03 15:49:12',
            ),
        ));
        
        
    }
}