<?php

use Illuminate\Database\Seeder;

class ProjectUnitsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('project_units')->delete();
        
        \DB::table('project_units')->insert(array (
            0 => 
            array (
                'id' => 13,
                'project_id' => 8,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1360000.0,
                'unit_area_from' => '125',
                'unit_area_to' => '174',
                'delivery_date' => '2016-07-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 15:06:37',
                'updated_at' => '2015-10-19 15:06:37',
            ),
            1 => 
            array (
                'id' => 14,
                'project_id' => 8,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1360000.0,
                'unit_area_from' => '125',
                'unit_area_to' => '174',
                'delivery_date' => '2016-07-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 1,
                'deleted_by' => 7,
                'created_at' => '2015-10-19 15:07:18',
                'updated_at' => '2015-10-19 15:08:06',
            ),
            2 => 
            array (
                'id' => 15,
                'project_id' => 9,
                'unit_type' => 7,
                'unit_finish' => 2,
                'starting_price' => 321000.0,
                'unit_area_from' => '62',
                'unit_area_to' => '96',
                'delivery_date' => '2017-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 15:18:40',
                'updated_at' => '2015-10-19 15:18:40',
            ),
            3 => 
            array (
                'id' => 16,
                'project_id' => 9,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 1155000.0,
                'unit_area_from' => '144',
                'unit_area_to' => '145',
                'delivery_date' => '2017-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 15:20:46',
                'updated_at' => '2015-10-19 15:20:46',
            ),
            4 => 
            array (
                'id' => 17,
                'project_id' => 10,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 439200.0,
                'unit_area_from' => '122',
                'unit_area_to' => '230',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 18:54:05',
                'updated_at' => '2015-10-19 18:54:05',
            ),
            5 => 
            array (
                'id' => 18,
                'project_id' => 11,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 3300000.0,
                'unit_area_from' => '267',
                'unit_area_to' => '287',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 19:06:15',
                'updated_at' => '2016-01-12 22:24:34',
            ),
            6 => 
            array (
                'id' => 19,
                'project_id' => 11,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1470000.0,
                'unit_area_from' => '150',
                'unit_area_to' => '300',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 19:16:48',
                'updated_at' => '2016-01-12 22:25:17',
            ),
            7 => 
            array (
                'id' => 20,
                'project_id' => 12,
                'unit_type' => 2,
                'unit_finish' => 2,
                'starting_price' => 2840000.0,
                'unit_area_from' => '248',
                'unit_area_to' => '267',
                'delivery_date' => '2018-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 19:26:11',
                'updated_at' => '2015-10-19 19:26:11',
            ),
            8 => 
            array (
                'id' => 21,
                'project_id' => 12,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 2500000.0,
                'unit_area_from' => '250',
                'unit_area_to' => '278',
                'delivery_date' => '2018-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 19:30:20',
                'updated_at' => '2015-10-19 19:30:20',
            ),
            9 => 
            array (
                'id' => 22,
                'project_id' => 13,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 9200000.0,
                'unit_area_from' => '303',
                'unit_area_to' => '444',
                'delivery_date' => '2018-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 19:42:30',
                'updated_at' => '2015-10-19 19:42:30',
            ),
            10 => 
            array (
                'id' => 23,
                'project_id' => 13,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 4000000.0,
                'unit_area_from' => '257',
                'unit_area_to' => '307',
                'delivery_date' => '2018-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2015-10-19 19:44:36',
                'updated_at' => '2015-10-19 19:44:36',
            ),
            11 => 
            array (
                'id' => 24,
                'project_id' => 11,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 1681650.0,
                'unit_area_from' => '175',
                'unit_area_to' => '283',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:21:34',
                'updated_at' => '2016-01-12 22:25:34',
            ),
            12 => 
            array (
                'id' => 25,
                'project_id' => 14,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 9000000.0,
                'unit_area_from' => '586',
                'unit_area_to' => '871',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:30:03',
                'updated_at' => '2016-01-12 22:30:03',
            ),
            13 => 
            array (
                'id' => 26,
                'project_id' => 14,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 6800000.0,
                'unit_area_from' => '500',
                'unit_area_to' => '501',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:30:56',
                'updated_at' => '2016-01-12 22:30:56',
            ),
            14 => 
            array (
                'id' => 27,
                'project_id' => 14,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 4500000.0,
                'unit_area_from' => '400',
                'unit_area_to' => '401',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:31:30',
                'updated_at' => '2016-01-12 22:31:30',
            ),
            15 => 
            array (
                'id' => 28,
                'project_id' => 14,
                'unit_type' => 16,
                'unit_finish' => 2,
                'starting_price' => 4000000.0,
                'unit_area_from' => '420',
                'unit_area_to' => '450',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:32:54',
                'updated_at' => '2016-01-12 22:32:54',
            ),
            16 => 
            array (
                'id' => 29,
                'project_id' => 15,
                'unit_type' => 5,
                'unit_finish' => 1,
                'starting_price' => 1740000.0,
                'unit_area_from' => '250',
                'unit_area_to' => '428',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:36:18',
                'updated_at' => '2016-01-12 22:36:18',
            ),
            17 => 
            array (
                'id' => 30,
                'project_id' => 15,
                'unit_type' => 7,
                'unit_finish' => 1,
                'starting_price' => 600000.0,
                'unit_area_from' => '127',
                'unit_area_to' => '200',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:36:58',
                'updated_at' => '2016-01-12 22:36:58',
            ),
            18 => 
            array (
                'id' => 31,
                'project_id' => 16,
                'unit_type' => 2,
                'unit_finish' => 2,
                'starting_price' => 805200.0,
                'unit_area_from' => '160',
                'unit_area_to' => '161',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:42:45',
                'updated_at' => '2016-01-12 22:42:45',
            ),
            19 => 
            array (
                'id' => 32,
                'project_id' => 16,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 260000.0,
                'unit_area_from' => '85',
                'unit_area_to' => '135',
                'delivery_date' => '2018-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:43:15',
                'updated_at' => '2016-01-12 22:43:15',
            ),
            20 => 
            array (
                'id' => 33,
                'project_id' => 17,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 2964000.0,
                'unit_area_from' => '262',
                'unit_area_to' => '263',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:45:35',
                'updated_at' => '2016-01-12 22:45:35',
            ),
            21 => 
            array (
                'id' => 34,
                'project_id' => 17,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 2451000.0,
                'unit_area_from' => '212',
                'unit_area_to' => '228',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:46:06',
                'updated_at' => '2016-01-12 22:46:06',
            ),
            22 => 
            array (
                'id' => 35,
                'project_id' => 18,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 17000000.0,
                'unit_area_from' => '608',
                'unit_area_to' => '878',
                'delivery_date' => '2016-01-12',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:47:51',
                'updated_at' => '2016-01-12 22:47:51',
            ),
            23 => 
            array (
                'id' => 36,
                'project_id' => 19,
                'unit_type' => 17,
                'unit_finish' => 2,
                'starting_price' => 4415000.0,
                'unit_area_from' => '240',
                'unit_area_to' => '435',
                'delivery_date' => '2018-01-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => 7,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-01-12 22:53:41',
                'updated_at' => '2016-01-12 22:59:26',
            ),
            24 => 
            array (
                'id' => 37,
                'project_id' => 20,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 6000000.0,
                'unit_area_from' => '354',
                'unit_area_to' => '355',
                'delivery_date' => '2018-12-31',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-03-16 15:10:18',
                'updated_at' => '2016-03-16 15:10:18',
            ),
            25 => 
            array (
                'id' => 38,
                'project_id' => 20,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 3860000.0,
                'unit_area_from' => '250',
                'unit_area_to' => '360',
                'delivery_date' => '2018-12-31',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-03-16 15:11:18',
                'updated_at' => '2016-03-16 15:11:18',
            ),
            26 => 
            array (
                'id' => 39,
                'project_id' => 20,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 3000000.0,
                'unit_area_from' => '240',
                'unit_area_to' => '245',
                'delivery_date' => '2018-12-31',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-03-16 15:12:00',
                'updated_at' => '2016-03-16 15:12:00',
            ),
            27 => 
            array (
                'id' => 40,
                'project_id' => 21,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 4411600.0,
                'unit_area_from' => '340',
                'unit_area_to' => '345',
                'delivery_date' => '2018-12-31',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-03-18 22:07:53',
                'updated_at' => '2016-03-18 22:07:53',
            ),
            28 => 
            array (
                'id' => 41,
                'project_id' => 21,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 3000000.0,
                'unit_area_from' => '260',
                'unit_area_to' => '261',
                'delivery_date' => '2018-12-31',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-03-18 22:08:34',
                'updated_at' => '2016-03-18 22:08:34',
            ),
            29 => 
            array (
                'id' => 42,
                'project_id' => 22,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 6000000.0,
                'unit_area_from' => '327',
                'unit_area_to' => '1200',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-10-06 14:14:27',
                'updated_at' => '2016-10-06 14:14:27',
            ),
            30 => 
            array (
                'id' => 43,
                'project_id' => 22,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 4500000.0,
                'unit_area_from' => '279',
                'unit_area_to' => '316',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-10-06 14:15:23',
                'updated_at' => '2016-10-06 14:15:23',
            ),
            31 => 
            array (
                'id' => 44,
                'project_id' => 22,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 2800000.0,
                'unit_area_from' => '160',
                'unit_area_to' => '250',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-10-06 14:16:22',
                'updated_at' => '2016-10-06 14:16:22',
            ),
            32 => 
            array (
                'id' => 45,
                'project_id' => 22,
                'unit_type' => 2,
                'unit_finish' => 2,
                'starting_price' => 2700000.0,
                'unit_area_from' => '256',
                'unit_area_to' => '278',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-10-06 14:18:15',
                'updated_at' => '2016-10-06 14:18:15',
            ),
            33 => 
            array (
                'id' => 46,
                'project_id' => 22,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 1400000.0,
                'unit_area_from' => '150',
                'unit_area_to' => '268',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-10-06 14:19:48',
                'updated_at' => '2016-10-06 14:19:48',
            ),
            34 => 
            array (
                'id' => 47,
                'project_id' => 22,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1370000.0,
                'unit_area_from' => '135',
                'unit_area_to' => '253',
                'delivery_date' => '2019-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2016-10-06 14:21:09',
                'updated_at' => '2016-10-06 14:21:09',
            ),
            35 => 
            array (
                'id' => 48,
                'project_id' => 23,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 6500000.0,
                'unit_area_from' => '372',
                'unit_area_to' => '473',
                'delivery_date' => '2017-02-19',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-02-19 10:03:19',
                'updated_at' => '2017-02-19 10:03:19',
            ),
            36 => 
            array (
                'id' => 49,
                'project_id' => 23,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 4200000.0,
                'unit_area_from' => '258',
                'unit_area_to' => '298',
                'delivery_date' => '2017-02-19',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-02-19 10:04:05',
                'updated_at' => '2017-02-19 10:04:05',
            ),
            37 => 
            array (
                'id' => 50,
                'project_id' => 24,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 3600000.0,
                'unit_area_from' => '175',
                'unit_area_to' => '245',
                'delivery_date' => '2020-03-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-03-05 17:30:02',
                'updated_at' => '2017-03-05 17:30:02',
            ),
            38 => 
            array (
                'id' => 51,
                'project_id' => 24,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 2930000.0,
                'unit_area_from' => '142',
                'unit_area_to' => '209',
                'delivery_date' => '2020-03-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-03-05 17:31:39',
                'updated_at' => '2017-03-05 17:31:39',
            ),
            39 => 
            array (
                'id' => 52,
                'project_id' => 25,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 895000.0,
                'unit_area_from' => '143',
                'unit_area_to' => '260',
                'delivery_date' => '2018-04-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-04-04 17:29:54',
                'updated_at' => '2017-04-04 17:29:54',
            ),
            40 => 
            array (
                'id' => 53,
                'project_id' => 27,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 6000000.0,
                'unit_area_from' => '82',
                'unit_area_to' => '195',
                'delivery_date' => '2019-05-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-05-17 18:56:39',
                'updated_at' => '2017-05-17 18:56:39',
            ),
            41 => 
            array (
                'id' => 54,
                'project_id' => 28,
                'unit_type' => 7,
                'unit_finish' => 1,
                'starting_price' => 990000.0,
                'unit_area_from' => '61',
                'unit_area_to' => '251',
                'delivery_date' => '2020-07-31',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-07-20 16:34:49',
                'updated_at' => '2017-07-20 16:34:49',
            ),
            42 => 
            array (
                'id' => 55,
                'project_id' => 29,
                'unit_type' => 2,
                'unit_finish' => 2,
                'starting_price' => 5580000.0,
                'unit_area_from' => '298',
                'unit_area_to' => '315',
                'delivery_date' => '2020-07-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-07-24 19:07:29',
                'updated_at' => '2017-07-24 19:07:29',
            ),
            43 => 
            array (
                'id' => 56,
                'project_id' => 29,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 5450000.0,
                'unit_area_from' => '287',
                'unit_area_to' => '288',
                'delivery_date' => '2020-07-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-07-24 19:08:40',
                'updated_at' => '2017-07-24 19:08:40',
            ),
            44 => 
            array (
                'id' => 57,
                'project_id' => 29,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 2330000.0,
                'unit_area_from' => '127',
                'unit_area_to' => '188',
                'delivery_date' => '2020-07-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-07-24 19:09:10',
                'updated_at' => '2017-07-24 19:09:10',
            ),
            45 => 
            array (
                'id' => 58,
                'project_id' => 30,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 0.0,
                'unit_area_from' => '250',
                'unit_area_to' => '310',
                'delivery_date' => '2018-08-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-08-06 16:43:20',
                'updated_at' => '2017-08-06 16:43:20',
            ),
            46 => 
            array (
                'id' => 59,
                'project_id' => 30,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1145000.0,
                'unit_area_from' => '130',
                'unit_area_to' => '205',
                'delivery_date' => '2018-08-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-08-06 16:44:02',
                'updated_at' => '2017-08-06 16:44:02',
            ),
            47 => 
            array (
                'id' => 60,
                'project_id' => 31,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 3165000.0,
                'unit_area_from' => '298',
                'unit_area_to' => '300',
                'delivery_date' => '2020-09-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-09-25 17:31:29',
                'updated_at' => '2017-09-25 17:31:29',
            ),
            48 => 
            array (
                'id' => 61,
                'project_id' => 31,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 2000000.0,
                'unit_area_from' => '192',
                'unit_area_to' => '217',
                'delivery_date' => '2020-09-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-09-25 17:32:02',
                'updated_at' => '2017-09-25 17:32:02',
            ),
            49 => 
            array (
                'id' => 62,
                'project_id' => 32,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 6600000.0,
                'unit_area_from' => '290',
                'unit_area_to' => '397',
                'delivery_date' => '2020-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-10-05 13:22:39',
                'updated_at' => '2017-10-05 13:22:39',
            ),
            50 => 
            array (
                'id' => 63,
                'project_id' => 32,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 3000000.0,
                'unit_area_from' => '177',
                'unit_area_to' => '207',
                'delivery_date' => '2020-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-10-05 13:23:23',
                'updated_at' => '2017-10-05 13:23:23',
            ),
            51 => 
            array (
                'id' => 64,
                'project_id' => 32,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 2700000.0,
                'unit_area_from' => '177',
                'unit_area_to' => '207',
                'delivery_date' => '2020-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-10-05 13:23:59',
                'updated_at' => '2017-10-05 13:23:59',
            ),
            52 => 
            array (
                'id' => 65,
                'project_id' => 32,
                'unit_type' => 7,
                'unit_finish' => 1,
                'starting_price' => 1400000.0,
                'unit_area_from' => '107',
                'unit_area_to' => '155',
                'delivery_date' => '2020-10-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-10-05 13:24:33',
                'updated_at' => '2017-10-05 13:24:33',
            ),
            53 => 
            array (
                'id' => 66,
                'project_id' => 33,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 17000000.0,
                'unit_area_from' => '455',
                'unit_area_to' => '456',
                'delivery_date' => '2020-11-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-11-02 16:47:01',
                'updated_at' => '2017-11-02 16:47:01',
            ),
            54 => 
            array (
                'id' => 67,
                'project_id' => 33,
                'unit_type' => 7,
                'unit_finish' => 2,
                'starting_price' => 4000000.0,
                'unit_area_from' => '171',
                'unit_area_to' => '176',
                'delivery_date' => '2020-11-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-11-02 16:50:11',
                'updated_at' => '2017-11-02 16:50:11',
            ),
            55 => 
            array (
                'id' => 68,
                'project_id' => 34,
                'unit_type' => 2,
                'unit_finish' => 2,
                'starting_price' => 2100000.0,
                'unit_area_from' => '230',
                'unit_area_to' => '413',
                'delivery_date' => '2020-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-12-29 17:12:28',
                'updated_at' => '2017-12-29 17:12:28',
            ),
            56 => 
            array (
                'id' => 69,
                'project_id' => 34,
                'unit_type' => 9,
                'unit_finish' => 2,
                'starting_price' => 1860000.0,
                'unit_area_from' => '180',
                'unit_area_to' => '264',
                'delivery_date' => '2020-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-12-29 17:14:28',
                'updated_at' => '2017-12-29 17:14:28',
            ),
            57 => 
            array (
                'id' => 70,
                'project_id' => 34,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1050000.0,
                'unit_area_from' => '102',
                'unit_area_to' => '218',
                'delivery_date' => '2020-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2017-12-29 17:15:07',
                'updated_at' => '2017-12-29 17:15:07',
            ),
            58 => 
            array (
                'id' => 71,
                'project_id' => 35,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 6000000.0,
                'unit_area_from' => '460',
                'unit_area_to' => '530',
                'delivery_date' => '2021-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2018-01-08 16:34:48',
                'updated_at' => '2018-01-08 16:34:48',
            ),
            59 => 
            array (
                'id' => 72,
                'project_id' => 35,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 4000000.0,
                'unit_area_from' => '279',
                'unit_area_to' => '280',
                'delivery_date' => '2021-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2018-01-08 16:35:27',
                'updated_at' => '2018-01-08 16:35:27',
            ),
            60 => 
            array (
                'id' => 73,
                'project_id' => 35,
                'unit_type' => 1,
                'unit_finish' => 2,
                'starting_price' => 1500000.0,
                'unit_area_from' => '127',
                'unit_area_to' => '190',
                'delivery_date' => '2021-12-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2018-01-08 16:36:02',
                'updated_at' => '2018-01-08 16:36:02',
            ),
            61 => 
            array (
                'id' => 74,
                'project_id' => 36,
                'unit_type' => 5,
                'unit_finish' => 2,
                'starting_price' => 6000000.0,
                'unit_area_from' => '246',
                'unit_area_to' => '251',
                'delivery_date' => '2021-01-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2018-01-17 12:59:45',
                'updated_at' => '2018-01-17 12:59:45',
            ),
            62 => 
            array (
                'id' => 75,
                'project_id' => 36,
                'unit_type' => 3,
                'unit_finish' => 2,
                'starting_price' => 5000000.0,
                'unit_area_from' => '245',
                'unit_area_to' => '246',
                'delivery_date' => '2021-01-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2018-01-17 13:00:25',
                'updated_at' => '2018-01-17 13:00:25',
            ),
            63 => 
            array (
                'id' => 76,
                'project_id' => 36,
                'unit_type' => 4,
                'unit_finish' => 2,
                'starting_price' => 4000000.0,
                'unit_area_from' => '208',
                'unit_area_to' => '291',
                'delivery_date' => '2021-01-01',
                'available' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'marked_deleted' => 0,
                'deleted_by' => NULL,
                'created_at' => '2018-01-17 13:03:08',
                'updated_at' => '2018-01-17 13:03:08',
            ),
        ));
        
        
    }
}