<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 5,
                'email' => 'amir_adel@outlook.com',
                'username' => 'Amir Adel',
                'password' => '$2y$10$8kLNsNh4pp/rkkG4B1BEMu2X61sJoRd9uhLsSrPawW7BSvBG.nQVe',
                'password_temp' => '',
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 1,
                'created_by' => 5,
                'updated_by' => 5,
                'remember_token' => 'Xevhke4XpqqU98bBPBbiJR4COICu5zITrvepXupYn49Em3hDjaoLE5TIKzET',
                'last_login' => '2017-04-12 15:52:38',
                'created_at' => '2014-11-15 23:37:23',
                'updated_at' => '2017-04-12 15:52:38',
            ),
            1 => 
            array (
                'id' => 6,
                'email' => 'amr@be-egy.com',
                'username' => 'Amr Farouk',
                'password' => '$2y$10$HgymcrZBNo6Lrhbbigfv/eY0zxlgBsQ8sqeenuUu9m9s9RfY0tGba',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-10-14 12:37:33',
                'role_id' => 2,
                'created_by' => 5,
                'updated_by' => 16,
                'remember_token' => 'touhWha8uIQeFmy2NfDnmEzUyUxB8BxzxyDqxERVmLKuMbwomHonx8XmLWwx',
                'last_login' => '2015-06-22 15:18:39',
                'created_at' => '2014-11-15 23:37:23',
                'updated_at' => '2015-10-14 12:37:33',
            ),
            2 => 
            array (
                'id' => 7,
                'email' => 'ali@nexthomeco.com',
                'username' => 'Ali Abdelsattar',
                'password' => '$2y$10$u4Q2/BuYohY0p7SpaxDj6ORUcdIB.g7A9wnOa47wqBLDwSMUeLk4S',
                'password_temp' => '',
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 1,
                'created_by' => 5,
                'updated_by' => 7,
                'remember_token' => 'YA5oYdyc8P6OjQ2ycUBvYeT5veZIamF68nc32mThS343RkpB76rWjMwNNDFj',
                'last_login' => '2018-02-20 13:46:58',
                'created_at' => '2015-01-21 07:03:42',
                'updated_at' => '2018-02-20 13:46:58',
            ),
            3 => 
            array (
                'id' => 8,
                'email' => 'info@be-egy.com',
                'username' => 'Marwa Amer',
                'password' => '$2y$10$FEELgEkvJkXhkmU19XjHY.2qLee2cA0AUi6GSM4LFhHC./TvF.5.W',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-10-14 12:37:42',
                'role_id' => 3,
                'created_by' => 5,
                'updated_by' => NULL,
                'remember_token' => 'wEGQpaZvPxXWYYCpviiJoJevPm85ikZkv2l1jdyLIpxInXG4ozqri2dSur9M',
                'last_login' => '2015-07-25 16:20:22',
                'created_at' => '2015-02-08 17:24:55',
                'updated_at' => '2015-10-14 12:37:42',
            ),
            4 => 
            array (
                'id' => 9,
                'email' => 'fares@be-egy.com',
                'username' => 'Mohamed Fares',
                'password' => '$2y$10$1sk6ZV4TjravwqfLO/36ku0F1aMFmC/Rq4LUey2b9nC09beuWWWPS',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-10-14 12:37:49',
                'role_id' => 2,
                'created_by' => 5,
                'updated_by' => 16,
                'remember_token' => 'PGIaYYDXMKZzkUyQZxndtzwt7qXW6FemPcMDHY5uPdLkk8CTij11crh55VQ1',
                'last_login' => '2015-08-12 23:08:39',
                'created_at' => '2015-02-08 18:23:12',
                'updated_at' => '2015-10-14 12:37:49',
            ),
            5 => 
            array (
                'id' => 11,
                'email' => 'heba.d@be-egy.com',
                'username' => 'Heba daoud',
                'password' => '$2y$10$mZaHEdvJSxb9S9R/QwMjCOe/TbAgFJODYq/xJpvFOyY3oyCJ43w3u',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-10-14 12:37:55',
                'role_id' => 2,
                'created_by' => 9,
                'updated_by' => NULL,
                'remember_token' => 'FzkaxCMvyA97V0Q3xD2lZQHiHWuXZnhpf5eT7gGkocgD7B0OrAcRPgTUdkp8',
                'last_login' => '2015-08-02 13:05:29',
                'created_at' => '2015-03-01 15:33:39',
                'updated_at' => '2015-10-14 12:37:55',
            ),
            6 => 
            array (
                'id' => 12,
                'email' => 'raafat.e@be-egy.com',
                'username' => 'Raafat Ezzat',
                'password' => '$2y$10$BPI5K4jHYVhw6JWNg/NYSOCgphwXy8bL5GcYUW1zz1mDJWSUtt12O',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-06-30 15:26:15',
                'role_id' => 2,
                'created_by' => 9,
                'updated_by' => 9,
                'remember_token' => 'GvCzOerqP6dlUcKWRnKoGQUIfHMg7NoSwskyo9qdDGyqEJnTq5dv2CxEg1C7',
                'last_login' => '2015-06-30 13:57:49',
                'created_at' => '2015-03-01 15:35:01',
                'updated_at' => '2015-06-30 15:26:15',
            ),
            7 => 
            array (
                'id' => 15,
                'email' => 'peter@be-egy.com',
                'username' => 'Peter Atef',
                'password' => '$2y$10$TrRjzR.Iaeb/QCN.ir5.teJvhJfNhsLGgxCn5GRFcGTbQ2GeZsaFe',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-10-14 12:38:03',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'OcxO6W3KRcIeEyrtGPqtZxyAKPRSjpYSMNXRbeA9Z7LIfBq08TlRQImH9fdy',
                'last_login' => '2015-08-13 13:39:31',
                'created_at' => '2015-05-19 13:43:28',
                'updated_at' => '2015-10-14 12:38:03',
            ),
            8 => 
            array (
                'id' => 16,
                'email' => 'crm@be-egy.com',
                'username' => 'crm@be-egy.com',
                'password' => '$2y$10$x2BHNSm2PQEWnHrwnPLsDeCfFqUZ1TH42NeLIIc/dDgQ8pEIluCvi',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2015-10-14 12:38:11',
                'role_id' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => '4MwOPxrWDTFSkRpd1zBg22KGMsCWtI6Ql7e3r2xZuqEuDhi6owLedIaOFxWU',
                'last_login' => '2015-08-17 17:40:03',
                'created_at' => '2015-06-25 23:28:14',
                'updated_at' => '2015-10-14 12:38:11',
            ),
            9 => 
            array (
                'id' => 17,
                'email' => 'peter@nexthomeco.com',
                'username' => 'Peter Atef - NEXT',
                'password' => '$2y$10$AOgfkUvRwxSLnkw4bioBZOb6oQJzfAoA9vzfyhb4V4jEvi2xFXh1W',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2017-08-19 13:28:56',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'remember_token' => 'a24vfJdBJFzUC29lRYWFAwa9r5DE9MlBBk7iMsQPlMosunATi4To1VY3lkEy',
                'last_login' => '2016-02-05 17:30:14',
                'created_at' => '2015-10-14 15:19:20',
                'updated_at' => '2017-08-19 13:28:56',
            ),
            10 => 
            array (
                'id' => 18,
                'email' => 'morgan@ezyadwords.com',
                'username' => 'Kevin Morgan',
                'password' => '$2y$10$KBRpQuFYP9SYU9rUgk/dEODNoRSM0b5B9WGDafaX3Ug14BQumDw9W',
                'password_temp' => '',
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 1,
                'created_by' => 5,
                'updated_by' => NULL,
                'remember_token' => '',
                'last_login' => NULL,
                'created_at' => '2015-11-17 00:15:17',
                'updated_at' => '2015-11-17 00:15:17',
            ),
            11 => 
            array (
                'id' => 19,
                'email' => 'a.kamal@nexthomeco.com',
                'username' => 'Ahmed Kamal',
                'password' => '$2y$10$fPYaNoClIUYRxP47dpTICuEGO7MrjZuR2MFkPnHcyxKZLMGdpOrhK',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2016-08-15 15:53:50',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'jexM3KTKz5yFMR7uuKYqHOYeUVjQcQvhrWpTjfGFFHFAwX2Wz8RzDywDdIbP',
                'last_login' => '2016-06-16 16:44:36',
                'created_at' => '2016-01-12 15:26:25',
                'updated_at' => '2016-08-15 15:53:50',
            ),
            12 => 
            array (
                'id' => 20,
                'email' => 'm.asaad@nexthomeco.com',
                'username' => 'Mohammed Asaad',
                'password' => '$2y$10$pcoIy6thRJdbhy0djzclluCKl/6l.h1WnOptw596lrwoKZwl5DaB6',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2017-02-27 16:48:57',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'mPthprNEYtLv8qalheeE88JTH4lVJGD3dfxpquzSsLe2mVh30nFx8JhUqtth',
                'last_login' => '2017-02-07 17:06:20',
                'created_at' => '2016-08-21 13:24:05',
                'updated_at' => '2017-02-27 16:48:57',
            ),
            13 => 
            array (
                'id' => 21,
                'email' => 'ahmedessamae1995@gmail.com',
                'username' => 'Admin',
                'password' => '$2y$10$5bzQ0a.JJVHcZViB3ojgTuKhxiLkBDzWtCYtcnWsOh1w4nykVDFeO',
                'password_temp' => '',
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 1,
                'created_by' => 5,
                'updated_by' => NULL,
                'remember_token' => 'vAhuaV1e114GhwGzaiMh3v4NrpTkW24FeVqYjXhd40rTMqACNc1ER1Y4hVeE',
                'last_login' => '2018-02-13 01:13:38',
                'created_at' => '2016-08-23 12:26:25',
                'updated_at' => '2018-02-13 01:13:38',
            ),
            14 => 
            array (
                'id' => 22,
                'email' => 'a.sary@nexthomeco.com',
                'username' => 'Ahmed Sary',
                'password' => '$2y$10$B2ofrgFBe3KkDv524yhFLunrKId45vk5lBi/CoUYGeWsdobzJdPlm',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2016-10-04 11:00:57',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => '5aveauJ0BnJ2qKmughTzgSjysBo8qRXiGoaBlm2s2vfreZdEsX7LCqWEYxvq',
                'last_login' => '2016-08-30 11:52:07',
                'created_at' => '2016-08-25 17:48:54',
                'updated_at' => '2016-10-04 11:00:57',
            ),
            15 => 
            array (
                'id' => 23,
                'email' => 'i.rady@nexthomeco.com',
                'username' => 'Ibrahim Rady',
                'password' => '$2y$10$QpP7/6RmfUCAp0NxQB8mPe.GR074GKZYA3ywSgubv5QDGVeCj/6Ci',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2016-11-17 11:34:35',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'BpVHAnkXfqHAzhOZrnGZeTkWJZ1d7nlU7YRBDTtUMtAoQEHRE9aE3N2FNsYC',
                'last_login' => '2016-11-16 11:15:40',
                'created_at' => '2016-08-25 17:50:38',
                'updated_at' => '2016-11-17 11:34:35',
            ),
            16 => 
            array (
                'id' => 24,
                'email' => 'Info@nexthomeco.com',
                'username' => 'Admin Coordinator',
                'password' => '$2y$10$ygFhM.4twbirVX3P9Si7duj5bpFBuD/sasYAXzD6huMpYYrOfEPV.',
                'password_temp' => '',
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 3,
                'created_by' => 7,
                'updated_by' => 7,
                'remember_token' => '56WySPmLWBpJtJ9Vcovf4hMvyteFMEFmfenPxu3SLDySGXRoUuwOEBbuSfcL',
                'last_login' => '2018-02-20 12:51:16',
                'created_at' => '2016-09-03 12:45:31',
                'updated_at' => '2018-02-20 12:51:16',
            ),
            17 => 
            array (
                'id' => 25,
                'email' => 'a.elmeligy@nexthomeco.com',
                'username' => 'Adham El Meligy',
                'password' => '$2y$10$JoHk.zLEbqcul9lklZ6biuj5JTk4WQbeGX13QzqnKiNvv8DIIAtM2',
                'password_temp' => '',
                'active' => 0,
                'deactivated_at' => '2017-06-28 18:26:15',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'Rjl7THHLFzL1cGKdM5fnNbXdOJ34wlQ04quxyKBoC8duACt4erDfhVudRjyM',
                'last_login' => '2017-06-28 11:10:35',
                'created_at' => '2016-09-06 16:22:41',
                'updated_at' => '2017-06-28 18:26:15',
            ),
            18 => 
            array (
                'id' => 26,
                'email' => 'mahinaz@nexthomeco.com',
                'username' => 'Mahinaz Koura',
                'password' => '$2y$10$GNtuFzL77Qpn7QHWDdtq.eGHdWzdLN4CV5bizILJabyA3ZqQ3cyd.',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2016-11-27 14:39:11',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'jvHFxCzVEbtpg6VjpiowvRRJkk3PQ31Fmyst6fQapwdSWDGvfOgHXqp8tVEj',
                'last_login' => '2016-11-27 14:18:49',
                'created_at' => '2016-10-09 15:45:29',
                'updated_at' => '2016-11-27 14:39:11',
            ),
            19 => 
            array (
                'id' => 27,
                'email' => 'amira@nexthomeco.com',
                'username' => 'Amira Emad',
                'password' => '$2y$10$yJfCcOEmsmUSHQKh859TuuBzi7eUVqGCL4i5PeNUhr.pW473wTXgC',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2016-11-27 14:39:19',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'LI6qhZF4Yn5UqJis3aeIE31V2QdVig87gJYvRtGV9dZ2NVpNbULAEFxBQrVr',
                'last_login' => '2016-11-16 12:39:42',
                'created_at' => '2016-11-10 11:01:43',
                'updated_at' => '2016-11-27 14:39:19',
            ),
            20 => 
            array (
                'id' => 28,
                'email' => 'heba@nexthomeco.com',
                'username' => 'Heba Shousha',
                'password' => '$2y$10$MON.MaJo5AUF628ijsF7ueHtfaqNFZlcYVsKiBIUdkTUtyqHcgvv2',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2017-11-14 12:44:25',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'gSE6k1doaF1fhpjSTOrZRlMwnozNHHHHicEcYZYQmUw8FlouPHJ5vPD4AHxW',
                'last_login' => '2017-11-13 09:19:47',
                'created_at' => '2016-12-04 17:23:04',
                'updated_at' => '2017-11-14 12:44:25',
            ),
            21 => 
            array (
                'id' => 29,
                'email' => 'm.Fawzy@nexthomeco.com',
                'username' => 'Mahmoud Fawzy',
                'password' => '$2y$10$3Bollhh6Evss2ttdH0ppbOqtuE3llD26rYinzExO7Yco7qJij6G0m',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'j8sHhXzkMmQ8rG2m2zwofYLETWQBNlL3UCjjw1mRgKPSxpUqnHj1TyskAMa5',
                'last_login' => '2017-12-28 14:29:01',
                'created_at' => '2017-01-29 15:42:54',
                'updated_at' => '2017-12-28 14:29:01',
            ),
            22 => 
            array (
                'id' => 30,
                'email' => 'm.deabes@nexthomeco.com',
                'username' => 'Mahmoud Deabes',
                'password' => '$2y$10$RVGfEUAOh5q4OB.0PfeF0.JfsWexeZ3z3k55GZIK17PN2sRXYkZFK',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'rdhIKw4oxV56KQ9oVN2t1jrFo7f63dZgEwnNHtvxZHA6ES2DQVawzymhocgh',
                'last_login' => '2018-02-19 12:49:44',
                'created_at' => '2017-04-10 17:57:29',
                'updated_at' => '2018-02-19 12:49:44',
            ),
            23 => 
            array (
                'id' => 31,
                'email' => 'M.Gabr@nexthomeco.com',
                'username' => 'Moustafa Gabr',
                'password' => '$2y$10$q3ntyrfNcqjd1DAFBwUBF.wXmLLMn4bVRA3O1dKV4DugRgM7Zc7PS',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'ir9kL9okS9tXd7ikfUrJhgU3GYUErSQXFPbrN3zLwQ0DnmSMGOwMrjhxcL0u',
                'last_login' => '2018-02-01 14:28:25',
                'created_at' => '2017-04-10 17:58:55',
                'updated_at' => '2018-02-01 14:28:25',
            ),
            24 => 
            array (
                'id' => 32,
                'email' => 'g.megahed@nexthomeco.com',
                'username' => 'Gamal Megahed',
                'password' => '$2y$10$dTCH.M0N3E/5.W52mYsxM.WWTJGwPPHfSBDUdWZPiza4tRsCKYDpW',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2017-04-29 18:57:47',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => '7oXUV0U16nwikjd0hb42jtIsAJqzvs7SG9UShp8dxxOqh01R1VF8ZnOLGoCr',
                'last_login' => '2017-04-15 13:09:27',
                'created_at' => '2017-04-10 18:00:35',
                'updated_at' => '2017-04-29 18:57:47',
            ),
            25 => 
            array (
                'id' => 33,
                'email' => 'a.nageeb@nexthomeco.com',
                'username' => 'Ali Nageeb',
                'password' => '$2y$10$Mc90/PxRa6UII3TcV1UKSOVtWd7YRYPN9uIPRoJZse0PFq5ipkj7a',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'Z4AHeLn5HBO26wHE8VoQMLK4erMZKGJfjaylFz0mjHUhQqOcSPyRzJJvm4qN',
                'last_login' => '2018-02-13 13:55:38',
                'created_at' => '2017-04-24 16:08:18',
                'updated_at' => '2018-02-13 13:55:38',
            ),
            26 => 
            array (
                'id' => 34,
                'email' => 'ahmedessam@gmail.com',
                'username' => 'ahmedessam',
                'password' => '$2y$10$YoV0c7euWXMBBnv41sXj2eMC2TZdkbexuzUT5r0MWse53i2WETK4C',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 3,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'f3AghjuB7ZXhBrjJPCLppysd4A1OxX4Y6499iAJLrotqQW1G5i5FIXtTxXcM',
                'last_login' => '2017-05-16 16:00:08',
                'created_at' => '2017-05-16 15:59:55',
                'updated_at' => '2017-05-16 16:00:28',
            ),
            27 => 
            array (
                'id' => 35,
                'email' => 'k.bexawy@nexthomeco.com',
                'username' => 'Karim Bexawy',
                'password' => '$2y$10$2WBUi1WyloUBJPocZ7T6DuLCY4/h06lmudDS/mqAS16tUsnPcbrA2',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2017-08-30 16:04:39',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => '6Bvo8KenittQRa8Gwrjn3ol8xcANvNb5tkR7q3Qk0pLfZSJtNWR57gnHiJ8T',
                'last_login' => '2017-08-29 14:55:33',
                'created_at' => '2017-07-23 15:27:10',
                'updated_at' => '2017-08-30 16:04:39',
            ),
            28 => 
            array (
                'id' => 36,
                'email' => 'o.elshamy@nexthomeco.com',
                'username' => 'Omar El Shamy',
                'password' => '$2y$10$fgtQC6I/bVO.k0UyTBIhuu0IO5QAb1EWi.bYCZwG497Q9MLKde6/O',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2017-12-29 17:19:23',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'GTTBOx9Mg9zr0pvy8MLqbow3XyLKhZcZCAkXjLQsSzvBmJO1QWxx8wlicybC',
                'last_login' => '2017-12-27 17:09:57',
                'created_at' => '2017-12-05 13:31:25',
                'updated_at' => '2017-12-29 17:19:23',
            ),
            29 => 
            array (
                'id' => 37,
                'email' => 'm.yousef@nexthomeco.com',
                'username' => 'Mohammed Youssef',
                'password' => '$2y$10$uiIfJNkRMOjteXeaSkaSGuyMOzkMKeGeMtXfWdoEJ6KnMan3NkC3u',
                'password_temp' => NULL,
                'active' => 0,
                'deactivated_at' => '2017-12-05 17:01:05',
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => 7,
                'remember_token' => NULL,
                'last_login' => '2017-12-05 13:56:47',
                'created_at' => '2017-12-05 13:32:22',
                'updated_at' => '2017-12-05 17:01:05',
            ),
            30 => 
            array (
                'id' => 38,
                'email' => 'a.abdelaal@nexthomeco.com',
                'username' => 'Abd El Rahman ',
                'password' => '$2y$10$KxdUhs1yw5mtJxYWnqpD7uptqkL/J0KJnXOV7crIUJwM99JNzuoaC',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'VL50obIvBMaIL8FPc2e2EyPexbMEyu2eiGUFifxKTToYr7U0RclsRBtXbZzi',
                'last_login' => '2018-02-05 15:38:33',
                'created_at' => '2018-01-16 12:32:35',
                'updated_at' => '2018-02-05 15:38:33',
            ),
            31 => 
            array (
                'id' => 39,
                'email' => 'a.omran@nexthomeco.com',
                'username' => 'Ahmed Omran',
                'password' => '$2y$10$jCP9JUZdofRA/iwJC8AJCuca74LDLvcr5UKbxyhu3zggQrEGWVKBa',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => NULL,
                'last_login' => NULL,
                'created_at' => '2018-02-19 15:19:09',
                'updated_at' => '2018-02-19 15:19:09',
            ),
            32 => 
            array (
                'id' => 40,
                'email' => 'm.khateeb@nexthomeco.com',
                'username' => 'Mohammed El Khateeb',
                'password' => '$2y$10$LvUtTXB/yRX8iMzXWye9vOoyAF3KLjpdLnMIti2yMf2/zdzoUbxgi',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'hpgAd7chQO3ePkjJtYM076W2fnd13x5xsTmpaFYFHGALgYSIVh3mTOXC07NZ',
                'last_login' => '2018-02-19 16:56:20',
                'created_at' => '2018-02-19 15:20:01',
                'updated_at' => '2018-02-19 16:56:20',
            ),
            33 => 
            array (
                'id' => 41,
                'email' => 'a.talaat@nexthomeco.com',
                'username' => 'Ahmed Talaat',
                'password' => '$2y$10$H9RomE9.1jUC/4fP2omjQu/er0zOIOWorIsK5nElNiZ0Az4VbrjPO',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 2,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => NULL,
                'last_login' => '2018-02-19 17:02:05',
                'created_at' => '2018-02-19 15:22:09',
                'updated_at' => '2018-02-19 17:02:05',
            ),
            34 => 
            array (
                'id' => 42,
                'email' => 'soly@yahoo.com',
                'username' => 'Soliman',
                'password' => '$2y$10$.42wltSE8wb7sKhTSIxF2e1Mh52CbbYjrIeF5Kd7DiZOmMDvMceES',
                'password_temp' => NULL,
                'active' => 1,
                'deactivated_at' => NULL,
                'role_id' => 1,
                'created_by' => 7,
                'updated_by' => NULL,
                'remember_token' => 'XUX0LzzZs1iLEy27MSFcgyY79n7iiEkGY1aNXMaXUUDmy8jIpRXufujHz8tS',
                'last_login' => '2018-02-19 18:45:57',
                'created_at' => '2018-02-19 17:19:48',
                'updated_at' => '2018-02-19 18:45:57',
            ),
        ));
        
        
    }
}